### ISSUE TITLE
Add affiliation field

### ISSUE THREAD

**Issue by diokk** [tushargit/edx_Activity#8]
Hello, I want to add affiliation field. But you have two different tutorial. Which one should I follow? this one or the one in this link https://github.com/tushargit/edx_Activity/blob/master/implementation_of_state_and_city_in_LMS_registration_form_using_ajax.md

**Comment by tushargit** [comment]
can you explain me your requirement little more.In this doc ,you can create drop down using ajax.
For affilation you can normally create column affilation in database table from that table you can populate drop down of affilation (poplulate dropdown from database is given in tutorial).

**Comment by tushargit** [comment]
I guess you had cleared your issues .So I am closing this issue.
