### ISSUE TITLE
TASK: [common | Install role-independent useful system packages] **************

### ISSUE THREAD

**Issue by manhvt** [tushargit/edx_Activity#9]
failed: [localhost] => {"failed": true}
msg: Could not fetch updated apt files

FATAL: all hosts have already failed -- aborting

**Comment by tushargit** [comment]
Please send  me complete  error .But I think issue is related to your proxy settings or internet connection.

**Comment by tushargit** [comment]
I guess you had cleared your issues .So I am closing this.
